package ship.f.engine.client.utils.serverdrivenui2

import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import ship.f.engine.client.utils.serverdrivenui2.ext.WithState2
import ship.f.engine.client.utils.serverdrivenui2.state.Box2
import ship.f.engine.client.utils.serverdrivenui3.state.*
import ship.f.engine.shared.utils.serverdrivenui2.client3.Client3
import ship.f.engine.shared.utils.serverdrivenui2.client3.Client3.Companion.client3
import ship.f.engine.shared.utils.serverdrivenui2.ext.sduiLog
import ship.f.engine.shared.utils.serverdrivenui2.state.*

@Composable
fun Render(
    state: State2,
    modifier: Modifier = Modifier,
    client: Client3 = client3,
) {
    client.apply {
        if (state.id.isAutoGenerated) {
            RenderStatic(
                state = state,
                modifier = modifier
            )
        } else {
            RenderDynamic(
                state = state,
                modifier = modifier,
                client = client,
            )
        }
    }
}

@Composable
fun RenderDynamic(
    state: State2,
    modifier: Modifier = Modifier,
    client: Client3 = client3,
) {
    client.apply {
        when (state) {
            is BoxState2 -> getReactiveOrNull<BoxState2>(state.path3)?.let { Box2(it, modifier) } ?: Text("This view is not available right now")
            is ButtonState2 -> getReactiveOrNull<ButtonState2>(state.path3)?.let { Button2(it, modifier) } ?: Text("This view is not available right now")
            is CardState2 -> getReactiveOrNull<CardState2>(state.path3)?.let { Card2(it, modifier) } ?: Text("This view is not available right now")
            is CheckboxState2 -> getReactiveOrNull<CheckboxState2>(state.path3)?.let { CheckBox2(it, modifier) } ?: Text("This view is not available right now")
            is ColumnState2 -> getReactiveOrNull<ColumnState2>(state.path3)?.let { Column2(it, modifier) } ?: Text("This view is not available right now")
            is HorizontalDividerState2 -> getReactiveOrNull<HorizontalDividerState2>(state.path3)?.let { HorizontalDivider2(it, modifier) } ?: Text("This view is not available right now")
            is ImageState2 -> getReactiveOrNull<ImageState2>(state.path3)?.let { Image2(it, modifier) } ?: Text("This view is not available right now")
            is VideoState2 -> getReactiveOrNull<VideoState2>(state.path3)?.let { Video2(it, modifier) } ?: Text("This view is not available right now")
            is LazyColumnState2 -> getReactiveOrNull<LazyColumnState2>(state.path3)?.let { LazyColumn2(it, modifier) } ?: Text("This view is not available right now")
            is LazyGridState2 -> getReactiveOrNull<LazyGridState2>(state.path3)?.let { LazyGrid2(it, modifier) } ?: Text("This view is not available right now")
            is LazyRowState2 -> getReactiveOrNull<LazyRowState2>(state.path3)?.let { LazyRow2(it, modifier) } ?: Text("This view is not available right now")
            is RowState2 -> getReactiveOrNull<RowState2>(state.path3)?.let { Row2(it, modifier) } ?: Text("This view is not available right now")
            is FlowRowState2 -> getReactiveOrNull<FlowRowState2>(state.path3)?.let { FlowRow2(it, modifier) } ?: Text("This view is not available right now")
            is ScreenState2 -> getReactiveOrNull<ScreenState2>(state.path3)?.let { Screen2(it, modifier) } ?: Text("This view is not available right now")
            is ScaffoldState2 -> getReactiveOrNull<ScaffoldState2>(state.path3)?.let { Scaffold2(it, modifier) } ?: Text("This view is not available right now")
            is SpacerState2 -> getReactiveOrNull<SpacerState2>(state.path3)?.let { Spacer2(it, modifier) } ?: Text("This view is not available right now")
            is SwitchState2 -> getReactiveOrNull<SwitchState2>(state.path3)?.let { Switch2(it, modifier) } ?: Text("This view is not available right now")
            is SearchState2 -> getReactiveOrNull<SearchState2>(state.path3)?.let { Search2(it, modifier) } ?: Text("This view is not available right now")
            is TextFieldState2 -> getReactiveOrNull<TextFieldState2>(state.path3)?.let { TextField2(it, modifier) } ?: Text("This view is not available right now")
            is TextState2 -> getReactiveOrNull<TextState2>(state.path3)?.let { Text2(it, modifier) } ?: Text("This view is not available right now")
            is VerticalDividerState2 -> getReactiveOrNull<VerticalDividerState2>(state.path3)?.let { VerticalDivider2(it, modifier) } ?: Text("This view is not available right now")
            is DropDownState2 -> getReactiveOrNull<DropDownState2>(state.path3)?.let { DropDown2(it, modifier) } ?: Text("This view is not available right now")
            is BuilderState2 -> getReactiveOrNull<BuilderState2>(state.path3)?.let { Builder2(it, modifier) } ?: Text("This view is not available right now")
            is FadeInState2 -> getReactiveOrNull<FadeInState2>(state.path3)?.let { FadeIn2(it, modifier) } ?: Text("This view is not available right now")
            is UnknownState2 -> getReactiveOrNull<UnknownState2>(state.path3)?.let { Unknown2(it, modifier) } ?: Text("This view is not available right now")
            is CameraGalleryState2 -> getReactiveOrNull<CameraGalleryState2>(state.path3)?.let { CameraGallery2(it, modifier) } ?: Text("This view is not available right now")
            is WebViewState2 -> getReactiveOrNull<WebViewState2>(state.path3)?.let { WebView2(it, modifier) } ?: Text("This view is not available right now")
            is DialogState2 -> getReactiveOrNull<DialogState2>(state.path3)?.let { Dialog2(it, modifier) } ?: Text("This view is not available right now")
            is VariantState2 -> getReactiveOrNull<VariantState2>(state.path3)?.let { Variant2(it, modifier) } ?: Text("This view is not available right now")
            is RefState2 -> getReactiveOrNull<State2>(state.path3)?.let { Render(state = it.value, modifier = modifier) } ?: Text("This view is not available right now")
        }
    }
}

@Composable
fun RenderStatic(
    state: State2,
    modifier: Modifier = Modifier,
) {
    state.WithState2(modifier) { modifier ->
        when (state) {
            is BoxState2 -> state.Box2(modifier = modifier)
            is ButtonState2 -> state.Button2(modifier = modifier)
            is CardState2 -> state.Card2(modifier = modifier)
            is CheckboxState2 -> state.CheckBox2(modifier = modifier)
            is ColumnState2 -> state.Column2(modifier = modifier)
            is HorizontalDividerState2 -> state.HorizontalDivider2(modifier = modifier)
            is ImageState2 -> state.Image2(modifier = modifier)
            is VideoState2 -> state.Video2(modifier = modifier)
            is LazyColumnState2 -> state.LazyColumn2(modifier = modifier)
            is LazyGridState2 -> state.LazyGrid2(modifier = modifier)
            is LazyRowState2 -> state.LazyRow2(modifier = modifier)
            is RowState2 -> state.Row2(modifier = modifier)
            is FlowRowState2 -> state.FlowRow2(modifier = modifier)
            is ScreenState2 -> state.Screen2(modifier = modifier)
            is ScaffoldState2 -> state.Scaffold2(modifier = modifier)
            is SpacerState2 -> state.Spacer2(modifier = modifier)
            is SwitchState2 -> state.Switch2(modifier = modifier)
            is SearchState2 -> state.Search2(modifier = modifier)
            is TextFieldState2 -> state.TextField2(modifier = modifier)
            is TextState2 -> state.Text2(modifier = modifier)
            is VerticalDividerState2 -> state.VerticalDivider2(modifier = modifier)
            is DropDownState2 -> state.DropDown2(modifier = modifier)
            is BuilderState2 -> state.Builder2(modifier = modifier)
            is FadeInState2 -> state.FadeIn2(modifier = modifier)
            is UnknownState2 -> state.Unknown2(modifier = modifier)
            is CameraGalleryState2 -> state.CameraGallery2(modifier = modifier)
            is WebViewState2 -> state.WebView2(modifier = modifier)
            is DialogState2 -> state.Dialog2(modifier = modifier)
            is VariantState2 -> state.Variant2(modifier = modifier)
            is RefState2 -> TODO()
        }
    }
}