package ship.f.engine.client.utils.serverdrivenui2

import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import ship.f.engine.client.utils.serverdrivenui2.ext.WithState2
import ship.f.engine.client.utils.serverdrivenui2.state.*
import ship.f.engine.shared.utils.serverdrivenui2.client.ClientHolder2.get
import ship.f.engine.shared.utils.serverdrivenui2.client.CommonClient2
import ship.f.engine.shared.utils.serverdrivenui2.ext.sduiLog
import ship.f.engine.shared.utils.serverdrivenui2.state.*

@Composable
fun Render(
    state: State2,
    modifier: Modifier = Modifier,
    client: CommonClient2 = get()
) {
    client.apply {
        sduiLog(state.path, tag = "filtered index > Render") { state.id.name == "testZone" }
        if (state.id.isAutoGenerated) {
            RenderStatic(
                state = state,
                modifier = modifier
            )
        } else {
            RenderDynamic(
                state = state,
                modifier = modifier,
                client = client,
            )
        }
    }
}

@Composable
fun RenderDynamic(
    state: State2,
    modifier: Modifier = Modifier,
    client: CommonClient2 = get()
) {
    client.apply {
        sduiLog("Rendering dynamic state: ${state.id} with ${state.path}", tag = "filtered index > Render") { state.id.name == "testZone" }
        when (state) {
            is BoxState2 -> Box2(s = getReactivePathState(state.path, state), m = modifier)
            is ButtonState2 -> Button2(s = getReactivePathState(state.path, state), m = modifier)
            is CardState2 -> Card2(s = getReactivePathState(state.path, state), m = modifier)
            is CheckboxState2 -> CheckBox2(s = getReactivePathState(state.path, state), m = modifier)
            is ColumnState2 -> Column2(s = getReactivePathState(state.path, state), m = modifier)
            is HorizontalDividerState2 -> HorizontalDivider2(s = getReactivePathState(state.path, state), m = modifier)
            is ImageState2 -> Image2(s = getReactivePathState(state.path, state), m = modifier)
            is VideoState2 -> Video2(s = getReactivePathState(state.path, state), m = modifier)
            is LazyColumnState2 -> LazyColumn2(s = getReactivePathState(state.path, state), m = modifier)
            is LazyGridState2 -> LazyGrid2(s = getReactivePathState(state.path, state), m = modifier)
            is LazyRowState2 -> LazyRow2(s = getReactivePathState(state.path, state), m = modifier)
            is RowState2 -> Row2(s = getReactivePathState(state.path, state), m = modifier)
            is FlowRowState2 -> FlowRow2(s = getReactivePathState(state.path, state), m = modifier)
            is ScreenState2 -> Screen2(s = getReactivePathState(state.path, state), m = modifier)
            is ScaffoldState2 -> Scaffold2(s = getReactivePathState(state.path, state), m = modifier)
            is SpacerState2 -> Spacer2(s = getReactivePathState(state.path, state), m = modifier)
            is SwitchState2 -> Switch2(s = getReactivePathState(state.path, state), m = modifier)
            is SearchState2 -> Search2(s = getReactivePathState(state.path, state), m = modifier)
            is TextFieldState2 -> TextField2(s = getReactivePathState(state.path, state), m = modifier)
            is TextState2 -> Text2(s = getReactivePathState(state.path, state), m = modifier)
            is VerticalDividerState2 -> VerticalDivider2(s = getReactivePathState(state.path, state), m = modifier)
            is DropDownState2 -> DropDown2(s = getReactivePathState(state.path, state), m = modifier)
            is BuilderState2 -> Builder2(s = getReactivePathState(state.path, state), m = modifier)
            is FadeInState2 -> FadeIn2(s = getReactivePathState(state.path, state), m = modifier)
            is UnknownState2 -> Unknown2(s = getReactivePathState(state.path, state), m = modifier)
            is CameraGalleryState2 -> CameraGallery2(s = getReactivePathState(state.path, state), m = modifier)
            is WebViewState2 -> WebView2(s = getReactivePathState(state.path, state), m = modifier)
            is DialogState2 -> Dialog2(s = getReactivePathState(state.path, state), m = modifier)
        }
    }
}

@Composable
fun RenderStatic(
    state: State2,
    modifier: Modifier = Modifier,
) {
    state.WithState2(modifier) { modifier ->
        sduiLog("Rendering static state: ${state.id} with ${state.path}", tag = "filtered index > Render") { state.id.name == "testZone" }
        when (state) {
            is BoxState2 -> state.Box2(modifier = modifier)
            is ButtonState2 -> state.Button2(modifier = modifier)
            is CardState2 -> state.Card2(modifier = modifier)
            is CheckboxState2 -> state.CheckBox2(modifier = modifier)
            is ColumnState2 -> state.Column2(modifier = modifier)
            is HorizontalDividerState2 -> state.HorizontalDivider2(modifier = modifier)
            is ImageState2 -> state.Image2(modifier = modifier)
            is VideoState2 -> state.Video2(modifier = modifier)
            is LazyColumnState2 -> state.LazyColumn2(modifier = modifier)
            is LazyGridState2 -> state.LazyGrid2(modifier = modifier)
            is LazyRowState2 -> state.LazyRow2(modifier = modifier)
            is RowState2 -> state.Row2(modifier = modifier)
            is FlowRowState2 -> state.FlowRow2(modifier = modifier)
            is ScreenState2 -> state.Screen2(modifier = modifier)
            is ScaffoldState2 -> state.Scaffold2(modifier = modifier)
            is SpacerState2 -> state.Spacer2(modifier = modifier)
            is SwitchState2 -> state.Switch2(modifier = modifier)
            is SearchState2 -> state.Search2(modifier = modifier)
            is TextFieldState2 -> state.TextField2(modifier = modifier)
            is TextState2 -> state.Text2(modifier = modifier)
            is VerticalDividerState2 -> state.VerticalDivider2(modifier = modifier)
            is DropDownState2 -> state.DropDown2(modifier = modifier)
            is BuilderState2 -> state.Builder2(modifier = modifier)
            is FadeInState2 -> state.FadeIn2(modifier = modifier)
            is UnknownState2 -> state.Unknown2(modifier = modifier)
            is CameraGalleryState2 -> state.CameraGallery2(modifier = modifier)
            is WebViewState2 -> state.WebView2(modifier = modifier)
            is DialogState2 -> state.Dialog2(modifier = modifier)
        }
    }
}